spring:
  application:
    name: secure-notes-dev
  security:
    user:
      name: dev
      password: password

  datasource:
    url: jdbc:mysql://localhost:3306/notes_db?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8100

# swagger-ui custom path
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
